name: news_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  retrofit: ^4.4.1
  get_it: ^8.0.0
  freezed_annotation: ^2.4.4
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.4.1
  flutter_zoom_drawer: ^3.2.0
  easy_image_viewer: ^1.5.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  envied: ^0.5.4+1
  pretty_dio_logger: ^1.4.0
  url_launcher: ^6.3.0


dev_dependencies:
  retrofit_generator: ^9.1.2
  build_runner: ^2.4.13
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  flutter_lints: ^5.0.0
  json_serializable: ^6.0.0
  envied_generator: ^0.5.4+1


flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
